default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      - id: yamlfmt 